apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"setup-model","namespace":"fbricon-dev"},"spec":{"containers":[{"command":["wget","--continue","--output-document","/mnt/models/model.gguf","https://huggingface.co/instructlab/Qwen2-0.5B-Instruct-GGUF/resolve/main/qwen2-0_5b-instruct-q2_k.gguf"],"image":"busybox","name":"download-model","volumeMounts":[{"mountPath":"/mnt/models/","name":"model-volume"}]}],"restartPolicy":"Never","volumes":[{"name":"model-volume","persistentVolumeClaim":{"claimName":"llm-qwen2-0_5b"}}]}}
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      download-model; cpu, memory limit for container download-model'
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2024-07-11T13:11:20Z"
  name: setup-model
  namespace: fbricon-dev
  resourceVersion: "2477367207"
  uid: 24974a01-f21d-4da5-92c5-0cfa042487f6
spec:
  containers:
  - command:
    - wget
    - --continue
    - --output-document
    - /mnt/models/model.gguf
    - https://huggingface.co/Qwen/Qwen2-0.5B-Instruct-GGUF/resolve/main/qwen2-0_5b-instruct-q2_k.gguf
    image: busybox
    imagePullPolicy: Always
    name: download-model
    resources:
      limits:
        cpu: "1"
        memory: 1000Mi
      requests:
        cpu: 10m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1014180000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/models/
      name: model-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cjnzj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-7n76l
  preemptionPolicy: PreemptLowerPriority
  priority: -3
  priorityClassName: sandbox-users-pods
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1014180000
    seLinuxOptions:
      level: s0:c119,c69
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: model-volume
    persistentVolumeClaim:
      claimName: llm-qwen2-0_5b
  - name: kube-api-access-cjnzj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-07-11T13:11:20Z"
    message: '0/20 nodes are available: persistentvolumeclaim "llm-qwen2-0_5b" not
      found. preemption: 0/20 nodes are available: 20 Preemption is not helpful for
      scheduling..'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Burstable
