apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-qwen2-05b
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Pod
metadata:
  name: setup-model
spec:
  containers:
  - command:
    - wget
    - --continue
    - --output-document
    - /mnt/models/model.gguf
    - https://huggingface.co/Qwen/Qwen2-0.5B-Instruct-GGUF/resolve/main/qwen2-0_5b-instruct-q2_k.gguf
    image: busybox
    name: download-model
    volumeMounts:
    - mountPath: /mnt/models/
      name: model-volume
  restartPolicy: Never
  volumes:
  - name: model-volume
    persistentVolumeClaim:
      claimName: llm-qwen2-05b
